---
- name: Installer Apache
  ansible.builtin.apt:
    name: apache2
    state: present
    update_cache: true
  when: ansible_facts["os_family"] == "Debian"

- name: Installer Php7
  ansible.builtin.apt:
    name: libapache2-mod-php7.4
    state: present
  when: ansible_facts["os_family"] == "Debian"

- name: Démarrer le service Apache
  ansible.builtin.service:
    name: apache2
    state: started
    enabled: true
  when: ansible_facts["os_family"] == "Debian"

- name: Copier le fichier phpinfo
  ansible.builtin.copy:
    src: info.php
    dest: /var/www/html/index.php
    owner: www-data
    group: www-data
    mode: 0664
  when: ansible_facts["os_family"] == "Debian"

- name: Install config file
  ansible.builtin.template:
    src: ./ports.conf.j2
    dest: /etc/apache2/ports.conf
    owner: www-data
    mode: "0644"
  notify:
    - Restart apache2
  when: ansible_facts["os_family"] == "Debian"

- name: Reload apache config
  tags:
    - reload
  ansible.builtin.shell:
    cmd: "killall -s SIGHUP apache2"
  when: ansible_facts["os_family"] == "Debian"

- name: Installer Apache
  ansible.builtin.dnf:
    name: httpd
    state: present
    update_cache: true
  when: ansible_facts["os_family"] == "RedHat"

- name: Installer Php7
  ansible.builtin.dnf:
    name: php
    state: present
  when: ansible_facts["os_family"] == "RedHat"

- name: Démarrer le service Apache
  ansible.builtin.service:
    name: httpd
    state: started
    enabled: true
  when: ansible_facts["os_family"] == "RedHat"

- name: Copier le fichier phpinfo
  ansible.builtin.copy:
    src: info.php
    dest: /var/www/html/index.php
    owner: apache
    group: apache
    mode: 0664
  when: ansible_facts["os_family"] == "RedHat"

- name: Reload apache config
  tags:
    - reload
  ansible.builtin.shell:
    cmd: "killall -s SIGHUP httpd"
  when: ansible_facts["os_family"] == "RedHat"
