---
- hosts: web_debian
  vars_files:
    - vars/main.yml
  roles:
    - apache
    - geerlingguy.firewall
- hosts: web_rocky  
  vars_files:
    - vars/main.yml
  roles :
    - apache
    - geerlingguy.firewall