---
- hosts: container
  vars_files:
    - vars/main.yml
  roles:
    - apache
    - { role: geerlingguy.firewall }
- hosts: local
  tags:
    - docker
  roles:
    - container
- hosts: arista
  # connection: network_cli
  # gather_facts: false
  tags:
    - arista
  roles:
    - show_version
    - eth
